### ISSUE TITLE
GAP website uses https

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/utils#10]
Since GAP website uses https instead of http, for the next release could you please change several occurrences of 

    http://www.gap-system.org/DevelopersPages/StefanKohl/

to 

    https://www.gap-system.org/DevelopersPages/StefanKohl/

in PackageInfo.g and documentation.

**Comment by cdwensley** [comment]
Corrections to the home pages for both Stefan and Frank have been made and version 0.47 released. 
However it turns out that there is a problem with the gh-pages release mechanism (specifically an old README is displayed at: https://gap-packages.github.io/utils/README.html) so a further release will be needed once this problem has been dealt with.

**Comment by cdwensley** [comment]
gh-pages now updated; version 0.48 released yesterday
